// <auto-generated />
using System;
using CapaDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CapaDatos.Migrations
{
    [DbContext(typeof(TiendaContext))]
    [Migration("20240308112116_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CapaDatos.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Direccion")
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int?>("Telefono")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CapaDatos.Models.DetalleXFactura", b =>
                {
                    b.Property<int>("IdDetalleXFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleXFactura"));

                    b.Property<int>("IdSupervisor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NroFactura")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Plato")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Valor")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("IdDetalleXFactura");

                    b.HasIndex("IdSupervisor");

                    b.HasIndex("NroFactura");

                    b.ToTable("DetalleXFacturas");
                });

            modelBuilder.Entity("CapaDatos.Models.Factura", b =>
                {
                    b.Property<int>("NroFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroFactura"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdMesero")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NroMesa")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("NroFactura");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMesero");

                    b.HasIndex("NroMesa");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("CapaDatos.Models.Mesa", b =>
                {
                    b.Property<int>("NroMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NroMesa"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int>("Puestos")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Reservada")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("NroMesa");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("CapaDatos.Models.Mesero", b =>
                {
                    b.Property<int>("IdMesero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesero"));

                    b.Property<int>("Antiguedad")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int>("Edad")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("IdMesero");

                    b.ToTable("Meseros");
                });

            modelBuilder.Entity("CapaDatos.Models.Supervisor", b =>
                {
                    b.Property<int>("IdSupervisor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSupervisor"));

                    b.Property<int>("Antiguedad")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<int>("Edad")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)");

                    b.HasKey("IdSupervisor");

                    b.ToTable("Supervisores");
                });

            modelBuilder.Entity("CapaDatos.Models.DetalleXFactura", b =>
                {
                    b.HasOne("CapaDatos.Models.Supervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("IdSupervisor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapaDatos.Models.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("NroFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("CapaDatos.Models.Factura", b =>
                {
                    b.HasOne("CapaDatos.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapaDatos.Models.Mesero", "Mesero")
                        .WithMany()
                        .HasForeignKey("IdMesero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapaDatos.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("NroMesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Mesa");

                    b.Navigation("Mesero");
                });
#pragma warning restore 612, 618
        }
    }
}
